name: Test PR Workflow
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**.as"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a GitHub script
        uses: actions/github-script@v5
        with:
          script: |
            const script = require('./script.js')
            console.log(script({github, context}))
